version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
